import { useState, useRef, useEffect, useCallback } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { 
  Download, RefreshCw, Save, Play, Clock, Filter, Grid, List, 
  CheckCircle2, Loader2, AlertTriangle, RotateCw, ExternalLink, Info,
  Timer, XCircle, Zap
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { GeneratedVideo } from "@/pages/CreativeReplicator";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { FailureInspectorModal } from "./FailureInspectorModal";

interface EnhancedResultsGalleryProps {
  videos: GeneratedVideo[];
  onRegenerate: () => void;
  setVideos: React.Dispatch<React.SetStateAction<GeneratedVideo[]>>;
  jobId?: string;
}

// HARD LIMITS - No infinite waits
const MAX_RETRIES = 4;
const POLL_INTERVAL = 3000;
const URL_VALIDATION_TIMEOUT_MS = 60000; // 60 seconds MAX for URL validation
const URL_VALIDATION_CHECK_INTERVAL = 5000; // Check every 5 seconds
const PIPELINE_TIMEOUT_MS = 600000; // 10 minutes MAX for entire pipeline
const AUTO_RECOVERY_DELAY_MS = 5000;

// Explicit pipeline states - no ambiguity
type PipelineState = 
  | 'queued'
  | 'generating'
  | 'encoding'
  | 'uploading'
  | 'validating_url'
  | 'ready'
  | 'failed'
  | 'timed_out';

interface PipelineError {
  stage: string;
  errorType: 'engine_error' | 'ffmpeg_error' | 'upload_error' | 'url_error' | 'timeout_error' | 'validation_error' | 'file_missing' | 'permission_denied';
  message: string;
  code?: string;
  details?: string;
  retryable: boolean;
  suggestedFix?: string;
}

interface VideoWithValidation extends GeneratedVideo {
  pipelineState: PipelineState;
  urlValidated: boolean;
  validationAttempts: number;
  validationStartTime?: number;
  stageStartTime?: number;
  pipelineError?: PipelineError;
  currentStage?: string;
  engineUsed?: string;
  retryCount?: number;
  metadata?: {
    retry_count?: number;
    fallback_mode?: string;
    engine_used?: string;
    pipeline_error?: PipelineError;
    pipeline_status?: Record<string, string>;
  };
}

// Clear failure reasons - NO generic messages
const FAILURE_REASONS: Record<string, string> = {
  'engine_error': 'Video engine returned no output',
  'ffmpeg_error': 'FFMPEG export failed during encoding',
  'upload_error': 'Upload failed - network timeout or storage error',
  'url_error': 'URL validation timed out - file not accessible',
  'timeout_error': 'Pipeline exceeded maximum allowed time (10 min)',
  'validation_error': 'Invalid video format or corrupted file',
  'file_missing': 'Video file not generated by pipeline',
  'permission_denied': 'Permission denied on storage bucket',
};

export const EnhancedResultsGallery = ({ videos, onRegenerate, setVideos, jobId }: EnhancedResultsGalleryProps) => {
  const [selectedVideos, setSelectedVideos] = useState<string[]>([]);
  const [viewMode, setViewMode] = useState<"grid" | "list">("grid");
  const [filterRatio, setFilterRatio] = useState<string | null>(null);
  const [videoModalOpen, setVideoModalOpen] = useState(false);
  const [selectedVideoForPlay, setSelectedVideoForPlay] = useState<GeneratedVideo | null>(null);
  const [retryingVideos, setRetryingVideos] = useState<Set<string>>(new Set());
  const [isPolling, setIsPolling] = useState(false);
  const [videoValidationState, setVideoValidationState] = useState<Record<string, VideoWithValidation>>({});
  const [failureModalOpen, setFailureModalOpen] = useState(false);
  const [selectedFailedVideo, setSelectedFailedVideo] = useState<VideoWithValidation | null>(null);
  const [pipelineStartTime] = useState<number>(Date.now());
  const [timers, setTimers] = useState<Record<string, number>>({});
  const videoRef = useRef<HTMLVideoElement>(null);
  const pollingRef = useRef<NodeJS.Timeout | null>(null);
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Timer update every second
  useEffect(() => {
    timerRef.current = setInterval(() => {
      setTimers(prev => {
        const updated: Record<string, number> = {};
        Object.entries(videoValidationState).forEach(([id, state]) => {
          if (state.stageStartTime && (state.pipelineState === 'validating_url' || state.pipelineState === 'generating' || state.pipelineState === 'encoding' || state.pipelineState === 'uploading')) {
            updated[id] = Math.floor((Date.now() - state.stageStartTime) / 1000);
          }
        });
        return updated;
      });
    }, 1000);

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [videoValidationState]);

  // Check for stuck jobs and auto-fail them
  useEffect(() => {
    const checkStuckJobs = () => {
      const now = Date.now();
      
      setVideoValidationState(prev => {
        const updated = { ...prev };
        let hasChanges = false;
        
        Object.entries(updated).forEach(([id, state]) => {
          // Check URL validation timeout (60s)
          if (state.pipelineState === 'validating_url' && state.stageStartTime) {
            const elapsed = now - state.stageStartTime;
            if (elapsed > URL_VALIDATION_TIMEOUT_MS) {
              hasChanges = true;
              updated[id] = {
                ...state,
                pipelineState: 'timed_out',
                pipelineError: {
                  stage: 'url_validation',
                  errorType: 'timeout_error',
                  message: 'URL validation timed out after 60 seconds',
                  retryable: true,
                  suggestedFix: 'File may not have been generated. Try retry with FFMPEG-only mode.',
                },
              };
              
              // Update video status in state
              setVideos(prevVideos => prevVideos.map(v => 
                v.id === id ? { ...v, status: 'failed' as const } : v
              ));
              
              // Update database
              supabase.from('video_variations')
                .update({ 
                  status: 'failed',
                  metadata: { 
                    error: 'URL validation timed out',
                    timed_out_at: new Date().toISOString(),
                  }
                })
                .eq('id', id);
            }
          }
          
          // Check pipeline timeout (10 min)
          if (state.stageStartTime && 
              !['ready', 'failed', 'timed_out'].includes(state.pipelineState)) {
            const totalElapsed = now - pipelineStartTime;
            if (totalElapsed > PIPELINE_TIMEOUT_MS) {
              hasChanges = true;
              updated[id] = {
                ...state,
                pipelineState: 'timed_out',
                pipelineError: {
                  stage: state.currentStage || 'unknown',
                  errorType: 'timeout_error',
                  message: 'Pipeline exceeded maximum allowed time (10 minutes)',
                  retryable: true,
                  suggestedFix: 'Try with a simpler engine or FFMPEG-only mode.',
                },
              };
              
              setVideos(prevVideos => prevVideos.map(v => 
                v.id === id ? { ...v, status: 'failed' as const } : v
              ));
            }
          }
        });
        
        return hasChanges ? updated : prev;
      });
    };
    
    const intervalId = setInterval(checkStuckJobs, 5000);
    return () => clearInterval(intervalId);
  }, [pipelineStartTime, setVideos]);

  // Initialize validation state from videos
  useEffect(() => {
    const initialState: Record<string, VideoWithValidation> = {};
    videos.forEach(video => {
      const existing = videoValidationState[video.id];
      if (!existing) {
        const hasError = video.status === 'failed' && (video as any).metadata?.pipeline_error;
        const isProcessing = video.status === 'processing';
        const isCompleted = video.status === 'completed';
        
        let pipelineState: PipelineState = 'queued';
        if (hasError) pipelineState = 'failed';
        else if (isCompleted && video.url) pipelineState = 'validating_url';
        else if (isProcessing) pipelineState = 'generating';
        
        initialState[video.id] = {
          ...video,
          pipelineState,
          urlValidated: false,
          validationAttempts: 0,
          stageStartTime: Date.now(),
          validationStartTime: isCompleted && video.url ? Date.now() : undefined,
          pipelineError: (video as any).metadata?.pipeline_error,
          currentStage: pipelineState,
          engineUsed: (video as any).metadata?.engine_used || video.engine,
          retryCount: (video as any).metadata?.retry_count || 0,
          metadata: (video as any).metadata,
        };
      }
    });
    
    if (Object.keys(initialState).length > 0) {
      setVideoValidationState(prev => ({ ...prev, ...initialState }));
    }
  }, [videos]);

  // Check if file exists in storage (separate from URL accessibility)
  const checkFileExists = useCallback(async (videoId: string): Promise<{ exists: boolean; url?: string }> => {
    try {
      const { data, error } = await supabase
        .from('video_variations')
        .select('video_url, status, metadata')
        .eq('id', videoId)
        .single();
      
      if (error || !data) {
        return { exists: false };
      }
      
      // File exists if we have a URL from the database
      if (data.video_url) {
        return { exists: true, url: data.video_url };
      }
      
      return { exists: false };
    } catch {
      return { exists: false };
    }
  }, []);

  // Validate URL is accessible with hard timeout
  const validateVideoUrl = useCallback(async (
    videoId: string, 
    url: string,
    timeoutMs: number = 10000
  ): Promise<{ valid: boolean; reason?: string }> => {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
    
    try {
      const response = await fetch(url, { 
        method: 'HEAD',
        signal: controller.signal,
      });
      clearTimeout(timeoutId);
      
      if (response.ok) {
        const contentType = response.headers.get('content-type');
        const contentLength = response.headers.get('content-length');
        
        // Verify it's actually a video file
        if (contentType?.includes('video') || url.includes('/storage/')) {
          // Check file size is reasonable (at least 1KB)
          if (contentLength && parseInt(contentLength) < 1000) {
            return { valid: false, reason: 'File too small - likely corrupted or incomplete' };
          }
          return { valid: true };
        }
        return { valid: false, reason: 'Invalid content type - not a video file' };
      }
      
      return { valid: false, reason: `HTTP ${response.status}: ${response.statusText}` };
    } catch (err: any) {
      clearTimeout(timeoutId);
      if (err.name === 'AbortError') {
        return { valid: false, reason: 'Request timed out' };
      }
      return { valid: false, reason: err.message || 'Network error' };
    }
  }, []);

  // Main validation loop with timeout enforcement
  const validateCompletedVideos = useCallback(async () => {
    const now = Date.now();
    const videosToValidate = videos.filter(v => 
      v.status === 'completed' && 
      v.url && 
      videoValidationState[v.id]?.pipelineState === 'validating_url'
    );

    for (const video of videosToValidate) {
      if (!video.url) continue;
      
      const currentState = videoValidationState[video.id];
      if (!currentState) continue;
      
      // Hard timeout check
      const validationStartTime = currentState.validationStartTime || now;
      const elapsed = now - validationStartTime;
      
      if (elapsed > URL_VALIDATION_TIMEOUT_MS) {
        // TIMEOUT - Stop immediately, don't keep trying
        setVideoValidationState(prev => ({
          ...prev,
          [video.id]: {
            ...prev[video.id],
            pipelineState: 'timed_out',
            pipelineError: {
              stage: 'url_validation',
              errorType: 'timeout_error',
              message: `URL validation timed out after ${Math.floor(elapsed / 1000)}s`,
              retryable: true,
              suggestedFix: 'Check if file was generated. Try retry with FFMPEG-only mode.',
            },
          }
        }));
        
        setVideos(prev => prev.map(v => 
          v.id === video.id ? { ...v, status: 'failed' as const } : v
        ));
        
        // Update database
        await supabase.from('video_variations')
          .update({ 
            status: 'failed',
            metadata: { 
              error: 'URL validation timed out',
              validation_elapsed_ms: elapsed,
            }
          })
          .eq('id', video.id);
        
        continue;
      }
      
      // Check if file exists first
      const fileCheck = await checkFileExists(video.id);
      
      if (!fileCheck.exists) {
        // File doesn't exist - fail immediately, don't keep waiting
        setVideoValidationState(prev => ({
          ...prev,
          [video.id]: {
            ...prev[video.id],
            pipelineState: 'failed',
            pipelineError: {
              stage: 'file_check',
              errorType: 'file_missing',
              message: 'Video file not generated by pipeline',
              retryable: true,
              suggestedFix: 'Retry generation - the video engine may have failed silently.',
            },
          }
        }));
        
        setVideos(prev => prev.map(v => 
          v.id === video.id ? { ...v, status: 'failed' as const } : v
        ));
        
        continue;
      }
      
      // File exists - now validate URL accessibility
      const urlToValidate = fileCheck.url || video.url;
      const validationResult = await validateVideoUrl(video.id, urlToValidate);
      
      if (validationResult.valid) {
        // SUCCESS - Video is ready
        setVideoValidationState(prev => ({
          ...prev,
          [video.id]: {
            ...prev[video.id],
            pipelineState: 'ready',
            urlValidated: true,
            url: urlToValidate,
          }
        }));
        
        // Update video in main state
        setVideos(prev => prev.map(v => 
          v.id === video.id ? { ...v, url: urlToValidate, status: 'completed' as const } : v
        ));
      } else {
        // URL not accessible yet - increment attempts
        const attempts = (currentState.validationAttempts || 0) + 1;
        
        setVideoValidationState(prev => ({
          ...prev,
          [video.id]: {
            ...prev[video.id],
            validationAttempts: attempts,
          }
        }));
      }
    }
  }, [videos, videoValidationState, checkFileExists, validateVideoUrl, setVideos]);

  // Realtime subscription for video updates
  useEffect(() => {
    if (videos.length === 0) return;

    const channel = supabase
      .channel('video-variations-updates')
      .on(
        'postgres_changes',
        {
          event: 'UPDATE',
          schema: 'public',
          table: 'video_variations',
        },
        (payload) => {
          const updated = payload.new as any;
          
          // Update the video in state
          setVideos((prev) =>
            prev.map((video) =>
              video.id === updated.id
                ? {
                    ...video,
                    status: updated.status,
                    url: updated.video_url || video.url,
                    thumbnail: updated.thumbnail_url || video.thumbnail,
                    duration: updated.duration_sec || video.duration,
                  }
                : video
            )
          );

          // Update pipeline state based on database status
          if (updated.status === 'completed' && updated.video_url) {
            setVideoValidationState(prev => ({
              ...prev,
              [updated.id]: {
                ...prev[updated.id],
                url: updated.video_url,
                status: 'completed',
                pipelineState: 'validating_url',
                urlValidated: false,
                validationAttempts: 0,
                stageStartTime: Date.now(),
                validationStartTime: Date.now(),
              } as VideoWithValidation
            }));
          } else if (updated.status === 'failed') {
            const metadata = updated.metadata as any;
            setVideoValidationState(prev => ({
              ...prev,
              [updated.id]: {
                ...prev[updated.id],
                pipelineState: 'failed',
                pipelineError: metadata?.pipeline_error || {
                  stage: 'generation',
                  errorType: 'engine_error',
                  message: metadata?.error || 'Video generation failed',
                  retryable: true,
                },
              } as VideoWithValidation
            }));
          } else if (updated.status === 'processing') {
            setVideoValidationState(prev => ({
              ...prev,
              [updated.id]: {
                ...prev[updated.id],
                pipelineState: 'generating',
                stageStartTime: prev[updated.id]?.stageStartTime || Date.now(),
              } as VideoWithValidation
            }));
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [videos.length, setVideos]);

  // Polling for processing videos with validation
  useEffect(() => {
    const processingVideos = videos.filter(v => {
      const state = videoValidationState[v.id]?.pipelineState;
      return state && !['ready', 'failed', 'timed_out'].includes(state);
    });
    
    if (processingVideos.length === 0) {
      setIsPolling(false);
      if (pollingRef.current) {
        clearInterval(pollingRef.current);
        pollingRef.current = null;
      }
      return;
    }

    setIsPolling(true);

    pollingRef.current = setInterval(async () => {
      await pollVideoStatuses();
      await validateCompletedVideos();
    }, POLL_INTERVAL);

    return () => {
      if (pollingRef.current) {
        clearInterval(pollingRef.current);
      }
    };
  }, [videos, videoValidationState, validateCompletedVideos]);

  // Initial validation on mount
  useEffect(() => {
    validateCompletedVideos();
  }, [videos]);

  const pollVideoStatuses = async () => {
    const videoIds = videos.map(v => v.id);
    
    try {
      const { data, error } = await supabase
        .from('video_variations')
        .select('*')
        .in('id', videoIds);

      if (error) {
        console.error('Poll error:', error);
        return;
      }

      if (data) {
        setVideos(prev => prev.map(video => {
          const updated = data.find((d: any) => d.id === video.id);
          if (!updated) return video;

          return {
            ...video,
            status: updated.status as GeneratedVideo['status'],
            url: updated.video_url || video.url,
            thumbnail: updated.thumbnail_url || video.thumbnail,
            duration: updated.duration_sec || video.duration,
          };
        }));
      }
    } catch (err) {
      console.error('Polling error:', err);
    }
  };

  const handleRefreshResults = async () => {
    toast.info("Refreshing results...");
    await pollVideoStatuses();
    
    // Reset validation state for incomplete validations
    setVideoValidationState(prev => {
      const updated = { ...prev };
      Object.keys(updated).forEach(id => {
        if (updated[id].pipelineState === 'validating_url') {
          updated[id] = {
            ...updated[id],
            validationAttempts: 0,
            stageStartTime: Date.now(),
            validationStartTime: Date.now(),
          };
        }
      });
      return updated;
    });
    
    // Re-validate
    setTimeout(() => validateCompletedVideos(), 500);
    
    toast.success("Results refreshed");
  };

  const toggleSelect = (id: string) => {
    setSelectedVideos((prev) =>
      prev.includes(id) ? prev.filter((v) => v !== id) : [...prev, id]
    );
  };

  const selectAll = () => {
    const readyVideos = videos.filter(v => 
      videoValidationState[v.id]?.pipelineState === 'ready'
    );
    setSelectedVideos(readyVideos.map((v) => v.id));
  };

  const deselectAll = () => {
    setSelectedVideos([]);
  };

  const filteredVideos = filterRatio
    ? videos.filter((v) => v.ratio === filterRatio)
    : videos;

  const uniqueRatios = [...new Set(videos.map((v) => v.ratio))];

  const handleDownloadSelected = async () => {
    const readySelected = videos.filter(
      v => selectedVideos.includes(v.id) && 
           videoValidationState[v.id]?.pipelineState === 'ready' && 
           v.url
    );
    
    if (readySelected.length === 0) {
      toast.error("No ready videos selected for download");
      return;
    }

    toast.success(`Downloading ${readySelected.length} videos...`);
    
    for (const video of readySelected) {
      if (video.url) {
        const link = document.createElement("a");
        link.href = video.url;
        link.download = `${video.id}.mp4`;
        link.click();
      }
    }
  };

  const handleSaveToProjects = () => {
    const readyCount = videos.filter(
      v => selectedVideos.includes(v.id) && 
           videoValidationState[v.id]?.pipelineState === 'ready'
    ).length;
    toast.success(`Saved ${readyCount} videos to projects`);
  };

  const handlePlayVideo = (video: GeneratedVideo, e: React.MouseEvent) => {
    e.stopPropagation();
    
    const validationState = videoValidationState[video.id];
    
    if (validationState?.pipelineState !== 'ready') {
      if (validationState?.pipelineState === 'validating_url') {
        toast.info("Video is being validated. Please wait...");
      } else if (['generating', 'encoding', 'uploading', 'queued'].includes(validationState?.pipelineState || '')) {
        toast.info("Video is still processing. Please wait...");
      } else {
        toast.error("Video is not available. Check failure details.");
      }
      return;
    }
    
    if (!video.url) {
      toast.error("Video URL not available. Try refreshing.");
      return;
    }
    
    setSelectedVideoForPlay(video);
    setVideoModalOpen(true);
  };

  const handleRetryVideo = async (video: GeneratedVideo, e: React.MouseEvent) => {
    e.stopPropagation();
    
    const currentState = videoValidationState[video.id];
    const retryCount = currentState?.retryCount || 0;
    
    if (retryCount >= MAX_RETRIES) {
      toast.error("Maximum retries reached for this video");
      return;
    }
    
    if (retryingVideos.has(video.id)) return;
    
    setRetryingVideos(prev => new Set(prev).add(video.id));
    setFailureModalOpen(false);
    
    try {
      // Reset state to generating
      setVideoValidationState(prev => ({
        ...prev,
        [video.id]: {
          ...prev[video.id],
          pipelineState: 'generating',
          urlValidated: false,
          validationAttempts: 0,
          stageStartTime: Date.now(),
          pipelineError: undefined,
          retryCount: retryCount + 1,
        } as VideoWithValidation
      }));
      
      setVideos(prev => prev.map(v => 
        v.id === video.id ? { ...v, status: "processing" as const } : v
      ));
      
      // Determine retry mode
      const attemptNum = retryCount + 1;
      let mode = 'same engine';
      if (attemptNum === 3) mode = 'FFMPEG-only';
      if (attemptNum >= 4) mode = 'Safe mode';
      
      toast.info(`Retrying (attempt ${attemptNum}/4) using ${mode}...`);
      
      const { data, error } = await supabase.functions.invoke('ffmpeg-creative-engine', {
        body: {
          task: {
            taskType: 'retry-single',
            videoId: video.id,
          },
          config: {
            hookStyle: video.hookStyle,
            pacing: video.pacing,
            ratio: video.ratio,
          },
        },
      });

      if (error) {
        throw new Error(error.message || 'Retry request failed');
      }

      if (data?.pipelineError) {
        setVideoValidationState(prev => ({
          ...prev,
          [video.id]: {
            ...prev[video.id],
            pipelineState: 'failed',
            pipelineError: data.pipelineError,
            retryCount: retryCount + 1,
          } as VideoWithValidation
        }));
        
        setVideos(prev => prev.map(v => 
          v.id === video.id ? { ...v, status: "failed" as const } : v
        ));
        
        toast.error(`Retry failed: ${data.pipelineError.message}`);
      } else {
        toast.success('Retry started successfully');
      }

    } catch (err) {
      console.error('Retry error:', err);
      const errorMessage = err instanceof Error ? err.message : 'Unknown error';
      
      toast.error(`Failed to retry: ${errorMessage}`);
      
      setVideoValidationState(prev => ({
        ...prev,
        [video.id]: {
          ...prev[video.id],
          pipelineState: 'failed',
          pipelineError: {
            stage: 'retry',
            errorType: 'engine_error',
            message: errorMessage,
            retryable: retryCount + 1 < MAX_RETRIES,
            suggestedFix: 'Try again with a different engine or FFMPEG-only mode',
          },
          retryCount: retryCount + 1,
        } as VideoWithValidation
      }));
      
      setVideos(prev => prev.map(v => 
        v.id === video.id ? { ...v, status: "failed" as const } : v
      ));
    } finally {
      setRetryingVideos(prev => {
        const next = new Set(prev);
        next.delete(video.id);
        return next;
      });
    }
  };

  const handleOpenFailureInspector = (video: GeneratedVideo, e: React.MouseEvent) => {
    e.stopPropagation();
    const validationState = videoValidationState[video.id];
    if (validationState) {
      setSelectedFailedVideo(validationState);
      setFailureModalOpen(true);
    }
  };

  const handleRetryAllFailed = async () => {
    const failedVideos = videos.filter(v => {
      const state = videoValidationState[v.id]?.pipelineState;
      return state === 'failed' || state === 'timed_out';
    });
    for (const video of failedVideos) {
      await handleRetryVideo(video, { stopPropagation: () => {} } as any);
    }
  };

  // Calculate counts based on pipeline state
  const readyVideos = videos.filter(v => videoValidationState[v.id]?.pipelineState === 'ready');
  const processingVideos = videos.filter(v => {
    const state = videoValidationState[v.id]?.pipelineState;
    return state && ['queued', 'generating', 'encoding', 'uploading', 'validating_url'].includes(state);
  });
  const failedVideos = videos.filter(v => {
    const state = videoValidationState[v.id]?.pipelineState;
    return state === 'failed' || state === 'timed_out';
  });

  // TRUE completion check - no false positives
  const isFullyComplete = readyVideos.length === videos.length && videos.length > 0;
  const hasActiveWork = processingVideos.length > 0;
  const overallProgress = videos.length > 0 
    ? Math.round((readyVideos.length / videos.length) * 100) 
    : 0;

  const getVideoReadyState = (video: GeneratedVideo): PipelineState => {
    return videoValidationState[video.id]?.pipelineState || 'queued';
  };

  const formatTime = (seconds: number): string => {
    if (seconds < 60) return `${seconds}s`;
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  const getStateLabel = (state: PipelineState): string => {
    switch (state) {
      case 'queued': return 'Queued';
      case 'generating': return 'Generating';
      case 'encoding': return 'Encoding';
      case 'uploading': return 'Uploading';
      case 'validating_url': return 'Validating';
      case 'ready': return 'Ready';
      case 'failed': return 'Failed';
      case 'timed_out': return 'Timed Out';
      default: return 'Unknown';
    }
  };

  const getStateColor = (state: PipelineState): string => {
    switch (state) {
      case 'ready': return 'bg-green-500';
      case 'failed': return 'bg-destructive';
      case 'timed_out': return 'bg-orange-500';
      default: return 'bg-muted';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header with Progress */}
      <div className="flex items-center justify-between">
        <div className="space-y-2">
          <h2 className="text-xl font-semibold flex items-center gap-2">
            {hasActiveWork ? (
              <Loader2 className="w-5 h-5 text-orange-500 animate-spin" />
            ) : failedVideos.length > 0 && readyVideos.length === 0 ? (
              <XCircle className="w-5 h-5 text-destructive" />
            ) : isFullyComplete ? (
              <CheckCircle2 className="w-5 h-5 text-green-500" />
            ) : failedVideos.length > 0 ? (
              <AlertTriangle className="w-5 h-5 text-orange-500" />
            ) : (
              <CheckCircle2 className="w-5 h-5 text-green-500" />
            )}
            {hasActiveWork 
              ? `Generation In Progress (${processingVideos.length} active)` 
              : failedVideos.length > 0 && readyVideos.length === 0
                ? "All Generations Failed"
                : isFullyComplete
                  ? "Generation Complete"
                  : readyVideos.length > 0
                    ? `${readyVideos.length}/${videos.length} Ready`
                    : "Ready"
            }
          </h2>
          <div className="flex items-center gap-4 text-sm text-muted-foreground">
            {readyVideos.length > 0 && (
              <span className="text-green-500 flex items-center gap-1">
                <CheckCircle2 className="w-3 h-3" /> {readyVideos.length} ready
              </span>
            )}
            {processingVideos.length > 0 && (
              <span className="text-orange-500 flex items-center gap-1">
                <Loader2 className="w-3 h-3 animate-spin" /> {processingVideos.length} active
              </span>
            )}
            {failedVideos.length > 0 && (
              <span className="text-destructive flex items-center gap-1">
                <XCircle className="w-3 h-3" /> {failedVideos.length} failed
              </span>
            )}
          </div>
          {hasActiveWork && (
            <Progress value={overallProgress} className="h-2 w-64" />
          )}
        </div>
        <div className="flex gap-2">
          <Button
            onClick={handleRefreshResults}
            variant="outline"
            size="sm"
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Refresh
          </Button>
          {failedVideos.length > 0 && (
            <Button
              onClick={handleRetryAllFailed}
              variant="outline"
              className="border-orange-500/50 text-orange-500"
            >
              <RotateCw className="w-4 h-4 mr-2" />
              Retry Failed ({failedVideos.length})
            </Button>
          )}
          <Button onClick={onRegenerate} variant="outline">
            <Zap className="w-4 h-4 mr-2" />
            Generate More
          </Button>
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <Button
            variant="outline"
            size="sm"
            onClick={selectedVideos.length === readyVideos.length ? deselectAll : selectAll}
          >
            {selectedVideos.length === readyVideos.length && readyVideos.length > 0 ? "Deselect All" : "Select All Ready"}
          </Button>
          {selectedVideos.length > 0 && (
            <span className="text-sm text-muted-foreground">
              {selectedVideos.length} selected
            </span>
          )}
        </div>

        <div className="flex items-center gap-3">
          {/* Ratio Filter */}
          <div className="flex items-center gap-2">
            <Filter className="w-4 h-4 text-muted-foreground" />
            <div className="flex gap-1">
              <Button
                variant={filterRatio === null ? "secondary" : "ghost"}
                size="sm"
                onClick={() => setFilterRatio(null)}
              >
                All
              </Button>
              {uniqueRatios.map((ratio) => (
                <Button
                  key={ratio}
                  variant={filterRatio === ratio ? "secondary" : "ghost"}
                  size="sm"
                  onClick={() => setFilterRatio(ratio)}
                >
                  {ratio}
                </Button>
              ))}
            </div>
          </div>

          {/* View Mode */}
          <div className="flex border rounded-lg">
            <Button
              variant={viewMode === "grid" ? "secondary" : "ghost"}
              size="sm"
              className="rounded-r-none"
              onClick={() => setViewMode("grid")}
            >
              <Grid className="w-4 h-4" />
            </Button>
            <Button
              variant={viewMode === "list" ? "secondary" : "ghost"}
              size="sm"
              className="rounded-l-none"
              onClick={() => setViewMode("list")}
            >
              <List className="w-4 h-4" />
            </Button>
          </div>
        </div>
      </div>

      {/* Bulk Actions */}
      {selectedVideos.length > 0 && (
        <Card className="border-primary/50 bg-primary/5">
          <CardContent className="p-4 flex items-center justify-between">
            <span className="font-medium">
              {selectedVideos.length} videos selected
            </span>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={handleDownloadSelected}>
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
              <Button size="sm" onClick={handleSaveToProjects}>
                <Save className="w-4 h-4 mr-2" />
                Save to Projects
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Video Grid */}
      <div
        className={
          viewMode === "grid"
            ? "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"
            : "space-y-3"
        }
      >
        {filteredVideos.map((video) => {
          const pipelineState = getVideoReadyState(video);
          const validationState = videoValidationState[video.id];
          const isReady = pipelineState === 'ready';
          const isValidating = pipelineState === 'validating_url';
          const isProcessing = ['queued', 'generating', 'encoding', 'uploading'].includes(pipelineState);
          const isFailed = pipelineState === 'failed' || pipelineState === 'timed_out';
          const timer = timers[video.id] || 0;
          const timeoutProgress = isValidating ? Math.min((timer / 60) * 100, 100) : 0;
          
          return (
            <Card
              key={video.id}
              className={`overflow-hidden transition-all cursor-pointer ${
                selectedVideos.includes(video.id)
                  ? "ring-2 ring-primary border-primary"
                  : isFailed
                    ? "border-destructive/50"
                    : isReady
                      ? "border-green-500/50"
                      : "border-border/50 hover:border-border"
              }`}
              onClick={() => isReady && toggleSelect(video.id)}
            >
              {viewMode === "grid" ? (
                <div className="relative">
                  {/* Thumbnail / Placeholder */}
                  <div className="aspect-[9/16] bg-muted flex items-center justify-center relative overflow-hidden">
                    {isReady && video.thumbnail ? (
                      <img
                        src={video.thumbnail}
                        alt={`Variation ${video.id}`}
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <div className="flex flex-col items-center gap-2 text-muted-foreground p-4">
                        {isValidating ? (
                          <>
                            <Loader2 className="w-8 h-8 animate-spin text-orange-500" />
                            <span className="text-xs text-center">
                              Validating ({formatTime(timer)} / 60s)
                            </span>
                            <Progress value={timeoutProgress} className="h-1 w-20" />
                          </>
                        ) : isProcessing ? (
                          <>
                            <Loader2 className="w-8 h-8 animate-spin" />
                            <span className="text-xs text-center">{getStateLabel(pipelineState)}</span>
                            {timer > 0 && (
                              <span className="text-xs text-muted-foreground flex items-center gap-1">
                                <Timer className="w-3 h-3" /> {formatTime(timer)}
                              </span>
                            )}
                          </>
                        ) : isFailed ? (
                          <>
                            <XCircle className="w-8 h-8 text-destructive" />
                            <span className="text-xs text-center text-destructive font-medium">
                              {pipelineState === 'timed_out' ? 'Timed Out' : 'Failed'}
                            </span>
                            <span className="text-[10px] text-center text-muted-foreground px-2">
                              {validationState?.pipelineError?.message || 'Unknown error'}
                            </span>
                          </>
                        ) : (
                          <>
                            <Loader2 className="w-8 h-8 animate-spin" />
                            <span className="text-xs text-center">Queued</span>
                          </>
                        )}
                      </div>
                    )}

                    {/* Selection Checkbox - Only for ready videos */}
                    {isReady && (
                      <div className="absolute top-2 left-2 z-10">
                        <Checkbox
                          checked={selectedVideos.includes(video.id)}
                          onCheckedChange={() => toggleSelect(video.id)}
                          onClick={(e) => e.stopPropagation()}
                          className="bg-background/80"
                        />
                      </div>
                    )}

                    {/* Play Button - Only for ready videos */}
                    {isReady && (
                      <button
                        className="absolute inset-0 flex items-center justify-center bg-black/30 opacity-0 hover:opacity-100 transition-opacity"
                        onClick={(e) => handlePlayVideo(video, e)}
                      >
                        <div className="w-12 h-12 rounded-full bg-primary/90 flex items-center justify-center">
                          <Play className="w-6 h-6 text-white ml-1" />
                        </div>
                      </button>
                    )}

                    {/* Retry/Info for Failed */}
                    {isFailed && (
                      <div className="absolute bottom-2 right-2 z-10 flex gap-1">
                        <TooltipProvider>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button 
                                size="sm" 
                                variant="outline"
                                className="bg-background/80"
                                onClick={(e) => handleOpenFailureInspector(video, e)}
                              >
                                <Info className="w-3 h-3" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent side="top" className="max-w-xs">
                              <p className="text-sm">
                                {validationState?.pipelineError?.message || 'Click to view details'}
                              </p>
                            </TooltipContent>
                          </Tooltip>
                        </TooltipProvider>
                        <Button 
                          size="sm" 
                          variant="destructive"
                          onClick={(e) => handleRetryVideo(video, e)}
                          disabled={retryingVideos.has(video.id) || (validationState?.retryCount || 0) >= MAX_RETRIES}
                        >
                          {retryingVideos.has(video.id) ? (
                            <Loader2 className="w-3 h-3 animate-spin" />
                          ) : (
                            <>
                              <RotateCw className="w-3 h-3 mr-1" />
                              Retry
                            </>
                          )}
                        </Button>
                      </div>
                    )}

                    {/* Status Badge with Timer */}
                    <div className="absolute top-2 right-2">
                      <Badge 
                        variant={isReady ? "default" : isFailed ? "destructive" : "secondary"}
                        className={`${getStateColor(pipelineState)} text-white`}
                      >
                        {getStateLabel(pipelineState)}
                        {isValidating && timer > 0 && ` ${timer}s`}
                      </Badge>
                    </div>

                    {/* Engine/Retry indicator */}
                    {validationState?.engineUsed && (
                      <div className="absolute bottom-2 left-2">
                        <Badge variant="outline" className="bg-background/80 text-[10px]">
                          {validationState.engineUsed}
                          {(validationState.retryCount || 0) > 0 && (
                            <span className="ml-1 text-orange-500">
                              R{validationState.retryCount}
                            </span>
                          )}
                        </Badge>
                      </div>
                    )}
                  </div>

                  {/* Info Footer */}
                  <CardContent className="p-3 space-y-2">
                    <div className="flex items-center justify-between text-xs">
                      <Badge variant="outline">{video.ratio}</Badge>
                      {isReady && video.duration && (
                        <span className="text-muted-foreground flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {video.duration}s
                        </span>
                      )}
                    </div>
                    <div className="flex flex-wrap gap-1">
                      <Badge variant="secondary" className="text-xs">
                        {video.hookStyle}
                      </Badge>
                      <Badge variant="secondary" className="text-xs">
                        {video.pacing}
                      </Badge>
                    </div>
                  </CardContent>
                </div>
              ) : (
                // List View
                <CardContent className="p-4">
                  <div className="flex items-center gap-4">
                    {/* Thumbnail */}
                    <div className="w-20 h-36 bg-muted rounded flex items-center justify-center shrink-0">
                      {isReady && video.thumbnail ? (
                        <img
                          src={video.thumbnail}
                          alt={`Variation ${video.id}`}
                          className="w-full h-full object-cover rounded"
                        />
                      ) : isProcessing || isValidating ? (
                        <div className="text-center">
                          <Loader2 className="w-6 h-6 animate-spin text-muted-foreground mx-auto" />
                          {timer > 0 && (
                            <span className="text-[10px] text-muted-foreground block mt-1">
                              {formatTime(timer)}
                            </span>
                          )}
                        </div>
                      ) : isFailed ? (
                        <XCircle className="w-6 h-6 text-destructive" />
                      ) : (
                        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
                      )}
                    </div>

                    {/* Info */}
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge 
                          variant={isReady ? "default" : isFailed ? "destructive" : "secondary"}
                          className={`${getStateColor(pipelineState)} text-white`}
                        >
                          {getStateLabel(pipelineState)}
                        </Badge>
                        <Badge variant="outline">{video.ratio}</Badge>
                        {isReady && video.duration && (
                          <span className="text-sm text-muted-foreground flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {video.duration}s
                          </span>
                        )}
                        {isValidating && timer > 0 && (
                          <span className="text-sm text-orange-500 flex items-center gap-1">
                            <Timer className="w-3 h-3" />
                            {formatTime(timer)} / 60s
                          </span>
                        )}
                      </div>
                      <div className="flex flex-wrap gap-1 mb-2">
                        <Badge variant="secondary" className="text-xs">
                          {video.hookStyle}
                        </Badge>
                        <Badge variant="secondary" className="text-xs">
                          {video.pacing}
                        </Badge>
                        {validationState?.engineUsed && (
                          <Badge variant="secondary" className="text-xs">
                            {validationState.engineUsed}
                          </Badge>
                        )}
                      </div>
                      {isFailed && validationState?.pipelineError && (
                        <p className="text-xs text-destructive truncate">
                          {validationState.pipelineError.message}
                        </p>
                      )}
                    </div>

                    {/* Actions */}
                    <div className="flex items-center gap-2">
                      {isReady && (
                        <>
                          <Checkbox
                            checked={selectedVideos.includes(video.id)}
                            onCheckedChange={() => toggleSelect(video.id)}
                          />
                          <Button
                            size="sm"
                            variant="ghost"
                            onClick={(e) => handlePlayVideo(video, e)}
                          >
                            <Play className="w-4 h-4" />
                          </Button>
                        </>
                      )}
                      {isFailed && (
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={(e) => handleRetryVideo(video, e)}
                          disabled={retryingVideos.has(video.id) || (validationState?.retryCount || 0) >= MAX_RETRIES}
                        >
                          <RotateCw className="w-4 h-4 mr-1" />
                          Retry
                        </Button>
                      )}
                    </div>
                  </div>
                </CardContent>
              )}
            </Card>
          );
        })}
      </div>

      {/* Video Playback Modal */}
      <Dialog open={videoModalOpen} onOpenChange={setVideoModalOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Play className="w-5 h-5" />
              Video Preview
            </DialogTitle>
          </DialogHeader>
          {selectedVideoForPlay && selectedVideoForPlay.url && (
            <div className="space-y-4">
              <div className="aspect-[9/16] max-h-[70vh] bg-black rounded-lg overflow-hidden">
                <video
                  ref={videoRef}
                  src={selectedVideoForPlay.url}
                  controls
                  autoPlay
                  className="w-full h-full object-contain"
                />
              </div>
              <div className="flex justify-between items-center">
                <div className="flex gap-2">
                  <Badge variant="outline">{selectedVideoForPlay.ratio}</Badge>
                  <Badge variant="secondary">{selectedVideoForPlay.hookStyle}</Badge>
                  <Badge variant="secondary">{selectedVideoForPlay.pacing}</Badge>
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => window.open(selectedVideoForPlay.url!, '_blank')}
                  >
                    <ExternalLink className="w-4 h-4 mr-2" />
                    Open in New Tab
                  </Button>
                  <Button
                    size="sm"
                    onClick={() => {
                      const link = document.createElement('a');
                      link.href = selectedVideoForPlay.url!;
                      link.download = `${selectedVideoForPlay.id}.mp4`;
                      link.click();
                    }}
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                </div>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Failure Inspector Modal */}
      <FailureInspectorModal
        open={failureModalOpen}
        onOpenChange={setFailureModalOpen}
        video={selectedFailedVideo}
        onRetry={() => {
          if (selectedFailedVideo) {
            handleRetryVideo(selectedFailedVideo, { stopPropagation: () => {} } as any);
          }
        }}
        isRetrying={selectedFailedVideo ? retryingVideos.has(selectedFailedVideo.id) : false}
      />
    </div>
  );
};
