// UGC Generator Types
// Self-contained types for the UGC Video Factory module

// Job status states
export type UGCJobStatus = 'IDLE' | 'CREATED' | 'PROCESSING' | 'RENDERING' | 'DONE' | 'FAILED';

// Language and market options
export type UGCLanguage = 'ARABIC' | 'SPANISH' | 'ENGLISH' | 'FRENCH';
export type UGCMarket = 'SAUDI_ARABIA' | 'PANAMA' | 'USA' | 'FRANCE' | 'UAE';
export type UGCGender = 'MALE' | 'FEMALE' | 'ALL';

// Script input modes
export type UGCScriptMode = 'AI_AUTO' | 'UPLOAD' | 'MANUAL';

// Generated avatar from AI
export interface UGCGeneratedAvatar {
    id: string;
    imageUrl: string;
    gender: 'MALE' | 'FEMALE';
    market: UGCMarket;
    language: UGCLanguage;
    isSelected?: boolean;
}

// Avatar configuration
export interface UGCAvatarConfig {
    type: 'upload' | 'auto';
    imageFile?: File;
    imagePreview?: string;
    language?: UGCLanguage;
    market?: UGCMarket;
    gender?: UGCGender;
    generatedAvatars?: UGCGeneratedAvatar[];
    selectedAvatarId?: string;
}

// Uploaded script/voice file
export interface UGCUploadedScriptFile {
    id: string;
    file: File;
    type: 'script' | 'voice';
    name: string;
    content?: string;
}

// Manual script entry
export interface UGCManualScript {
    id: string;
    text: string;
    videoNumber: number;
}

// Script configuration
export interface UGCScriptConfig {
    mode: UGCScriptMode;
    uploadedFiles?: UGCUploadedScriptFile[];
    manualScripts?: UGCManualScript[];
    text?: string;
    voiceId?: string;
    isAutoGenerated?: boolean;
}

// Product category
export type UGCProductCategory = 'beauty' | 'tech' | 'fashion' | 'food' | 'health' | 'home' | 'general';

// Product configuration
export interface UGCProductConfig {
    images: File[];
    imagePreviews: string[];
    name: string;
    benefit: string;
    category?: UGCProductCategory;
}

// Batch variation options
export interface UGCVariationOptions {
    changeHook: boolean;
    changeCTA: boolean;
    changeSubtitleStyle: boolean;
    changeBackground: boolean;
}

// Batch settings
export interface UGCBatchSettings {
    videoCount: number;
    variations: UGCVariationOptions;
}

// Scene structure
export interface UGCSceneConfig {
    sceneNumber: 1 | 2 | 3 | 4 | 5;
    duration: number;
    type: 'hook' | 'context' | 'product_usage' | 'benefit' | 'cta';
    content: string;
}

// Video variant output
export interface UGCVideoVariant {
    id: string;
    variantNumber: number;
    status: UGCJobStatus;
    hookText?: string;
    ctaText?: string;
    subtitleStyle?: string;
    avatarProfileId?: string;
    avatarId?: string;
    scriptId?: string;
    framework?: string;
    marketingAngle?: string;
    scriptText?: string;
    voiceUrl?: string;
    outputUrl?: string;
    thumbnailUrl?: string;
    createdAt: Date;
    completedAt?: Date;
}

// Main batch job
export interface UGCBatchJob {
    id: string;
    status: UGCJobStatus;
    avatar: UGCAvatarConfig;
    script: UGCScriptConfig;
    product: UGCProductConfig;
    settings: UGCBatchSettings;
    scenes: UGCSceneConfig[];
    variants: UGCVideoVariant[];
    progress: number;
    currentStage: string;
    createdAt: Date;
    completedAt?: Date;
    error?: string;
}

// Voice option for ElevenLabs
export interface UGCVoiceOption {
    id: string;
    name: string;
    description: string;
    voiceId: string;
    sampleText: string;
    isCustom?: boolean;
    category?: 'premade' | 'cloned' | 'generated';
}

// Pipeline stages for progress display
export const UGC_PIPELINE_STAGES = [
    'Script Generation',
    'Script Review',
    'Avatar Generation',
    'Voice Generation',
    'Scene Planning',
    'Batch Variants',
    'Anti-Fatigue Check',
    'Rendering',
    'Quality Validation',
    'Finalizing',
] as const;

export type UGCPipelineStage = typeof UGC_PIPELINE_STAGES[number];

// Default values
export const DEFAULT_UGC_BATCH_SETTINGS: UGCBatchSettings = {
    videoCount: 5,
    variations: {
        changeHook: true,
        changeCTA: true,
        changeSubtitleStyle: true,
        changeBackground: true,
    },
};

export const DEFAULT_UGC_SCRIPT_CONFIG: UGCScriptConfig = {
    mode: 'AI_AUTO',
};

export const DEFAULT_UGC_SCENES: UGCSceneConfig[] = [
    { sceneNumber: 1, duration: 3, type: 'hook', content: '' },
    { sceneNumber: 2, duration: 5, type: 'context', content: '' },
    { sceneNumber: 3, duration: 6, type: 'product_usage', content: '' },
    { sceneNumber: 4, duration: 4, type: 'benefit', content: '' },
    { sceneNumber: 5, duration: 2, type: 'cta', content: '' },
];

export const DEFAULT_UGC_AVATAR_SETTINGS = {
    language: 'ENGLISH' as UGCLanguage,
    market: 'USA' as UGCMarket,
    gender: 'ALL' as UGCGender,
};
